services:
  - type: web
    name: rose-x-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_USERNAME
        sync: false
      - key: CHANNEL_JOIN_URL
        sync: false
